-- MySQL Script generated by MySQL Workbench
-- Thu Jun  3 19:02:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoas` (
  `PES_ID` INT NOT NULL AUTO_INCREMENT,
  `PES_NOME` VARCHAR(45) NOT NULL,
  `PES_DATA_NASC` DATE NOT NULL,
  `PES_UF` VARCHAR(2) NOT NULL,
  `PES_CIDADE` VARCHAR(45) NOT NULL,
  `PES_NOME_PAI` VARCHAR(45) NOT NULL,
  `PES_NOME_MAE` VARCHAR(45) NOT NULL,
  `PES_NUM_CARTORIO` INT NOT NULL,
  `PES_NUM_REGISTRO` INT NOT NULL,
  `PES_COD_USUARIO_CARTORIO` INT NOT NULL,
  PRIMARY KEY (`PES_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidades` (
  `CIDADE_ID` INT NOT NULL AUTO_INCREMENT,
  `CIDADE_NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CIDADE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `ESTADO_ID` INT NOT NULL AUTO_INCREMENT,
  `ESTADO_NOME` VARCHAR(45) NOT NULL,
  `ESTADO_SIGLA` VARCHAR(2) NOT NULL,
  `ESTADO_ID_CAPITAL` INT NOT NULL,
  PRIMARY KEY (`ESTADO_ID`),
  INDEX `ESTADO_ID_CAPITAL_idx` (`ESTADO_ID_CAPITAL` ASC) VISIBLE,
  CONSTRAINT `ESTADO_ID_CAPITAL`
    FOREIGN KEY (`ESTADO_ID_CAPITAL`)
    REFERENCES `mydb`.`cidades` (`CIDADE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
