<script src="<?= base_url('assets/plugins/datepicker/js/bootstrap-clockpicker.min.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/bootstrap-material-datetimepicker.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/bs-daterange-picker-init.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/clock-picker-init.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/daterangepicker.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/jquery-asColor.min.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/jquery-asColorPicker.init.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/jquery-asColorPicker.min.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/material-date-picker-init.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/pickadate-init.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/picker.date.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/picker.js')?>"></script>
<script src="<?= base_url('assets/plugins/datepicker/js/picker.time.js')?>"></script>
